#!/usr/bin/env bash
# Configure nginx server with 301 redirection


if ! grep -qF "\tserver_name;\n\trewrite ^redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4/$1 permanent;" /etc/nginx/sites-available/default; then
    sudo sed -i 's|\tserver_name _;|\tserver_name _;\n\trewrite ^redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4/$1 permanent;|' /etc/nginx/sites-available/default
fi

service nginx restart
