#!/usr/bin/env bash
# Configure nginx server with 301 redirection

if ! [ -x "$(command -v nginx)" ]; then
    apt update
    apt install -y nginx
    service nginx start
fi
echo "Hello World!" > /var/www/html/index.html

if ! grep -qF "    server_name;\n    rewrite ^redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4/$1 permanent;" /etc/nginx/sites-available/default; then
    sudo sed -i 's|    server_name _;|    server_name _;\n    rewrite ^redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4/$1 permanent;|' /etc/nginx/sites-available/default
fi

service nginx restart
