#!/usr/bin/env bash
# Configure nginx server with 301 redirection

if ! [ -x "$(command -v nginx)" ]; then
    apt update
    apt install -y nginx
fi

ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html
service nginx start

cp /etc/nginx/sites-available/default /etc/nginx/sites-available/temp

awk '
    {
        if ($0 == "\tserver_name _;") {
            print "\tserver_name _;"
            print "location /redirect_me {"
            print "\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4$request_uri;"
            print "\t}"
        } else {
            print $0
        }
    }
' /etc/nginx/sites-enabled/default > temp && mv temp /etc/nginx/sites-enabled/default

nginx -s reload
