#!/usr/bin/env bash
# Install latest release of HAProxy 2.8 for Ubuntu Focal (20.04 LTS)

sudo apt update
sudo apt install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt install haproxy=2.0.\* -y
echo '
frontend http_front
	bind *:80
	stats uri /haproxy?stats
	default_backend http_back

backend http_back
	balance roundrobin
	server 172649-web-01 54.237.68.149:80 check
	server 172649-web-02 54.160.76.194:80 check
' | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy > /dev/null
sudo service haproxy restart
