#!/usr/bin/env bash
# Set up non root user of nginx
service nginx start
sed -i '1s/^.*$/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
service nginx restart
