#!/usr/bin/env bash
# Set up non root user of nginx
sed -i 's/^#*.*user.*;$/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
